import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AdminWrapper } from "@/components/Context/admincontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HallSync",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <AdminWrapper>{children}</AdminWrapper>
        </>
      </body>
    </html>
  );
}
